### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [thiendn160794/Task.Controll#1]
### Overall
- :+1: Thank you, this is a really great submission, Nhat Thien Dang!
- It looks like you pushed a lot efforts on it. I love that way you  write down your challenges during develop Todo App.

### Good stuffs
- Great to see `FloatingActionButton`
- Nice implementing `TaskAdapter` by extending `ArrayAdapter`
- Good job implementing `interface`
- Great using `SQLite` to persist todo items.
- Use a `DialogFragment` instead of new Activity for editing items.
- Please remove the unnecesary line for clean code.
- :bug: Look like you got a bug when update the toto item. Let make it completed.

<img src='http://i.imgur.com/I5igRdC.gif' title='Bug' width='' alt='Bug' />

### Next step :boom: :boom: :boom:
- Let's schedule a quick call to confirm that this course is a right fit for you. 
- We also would like to know a little more about your experience. 
Please book a slot from [here](https://calendly.com/harley/15m).

**Comment by thiendn160794** [comment]
Sorry for the late reply, I have been very eager for your response.
I was so anxious.  I was not expect to receive your mail via github, ortherwise, I would have replied sooner. 
I have book a slot at 11:00am - Monday, February 13, 2017 as you have recommended. 
Sorry for the inconvenience.
